import streamlit as st
import pandas as pd
import joblib
import os
import matplotlib.pyplot as plt
import seaborn as sns
#from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.metrics import (
    confusion_matrix, 
    classification_report, 
    accuracy_score, 
    precision_score, 
    recall_score, 
    f1_score
)

# Page Configuration
st.set_page_config(page_title="Breast Cancer Predictor", layout="wide")

st.title("Breast Cancer Classification App")
st.markdown("Build for **ML Assignment 2** | BITS Pilani")

# Sidebar: Model Selection
st.sidebar.header("Model Configuration")
model_options = [
    "Logistic Regression", 
    "Decision Tree", 
    "kNN", 
    "Naive Bayes", 
    "Random Forest", 
    "XGBoost"
]
selected_model_name = st.sidebar.selectbox("Select Machine Learning Model", model_options)

# Helper: Load Model
def load_model(model_name):
    # Convert readable name to filename (e.g., "Logistic Regression" -> "logistic_regression.pkl")
    filename = model_name.replace(" ", "_").lower() + ".pkl"
    path = os.path.join("model", filename)
    if os.path.exists(path):
        return joblib.load(path)
    else:
        st.error(f"Model file not found at {path}. Please run train_models.py first.")
        return None

# Main App Logic
model = load_model(selected_model_name)

# Section 1: Dataset Upload
st.subheader("1. Upload Test Data (CSV)")
uploaded_file = st.file_uploader("Upload test CSV (must contain features + target/diagnosis)", type=["csv"])

if uploaded_file is not None and model is not None:
    # Load data
    df = pd.read_csv(uploaded_file)
    st.write("### Data Preview")
    st.dataframe(df.head())

    # Identify Target Column (Assuming 'target/diagnosis' or similar from your dataset)
    # We try to auto-detect, otherwise default to last column
    if 'diagnosis' in df.columns:
        target_col = 'diagnosis'
    else:
        target_col = df.columns[-1]

    # Prepare Features (X) and Target (y)
    X_test = df.drop(columns=[target_col])
    y_test = df[target_col]

    # Button to Predict
    if st.button(f"Run Predictions with {selected_model_name}"):
        try:
             
            y_pred = model.predict(X_test)

            # To show Accuracy Metric
            st.subheader("Model Performance")
            acc = accuracy_score(y_test, y_pred)
            st.metric(label="Total Accuracy Score", value=f"{acc:.2%}")

            st.subheader("Model Performance Summary")

            # Create a clean dictionary for the table
            summary_data = {
                "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
                "Score": [
                    f"{accuracy_score(y_test, y_pred):.4f}",
                    f"{precision_score(y_test, y_pred):.4f}",
                    f"{recall_score(y_test, y_pred):.4f}",
                    f"{f1_score(y_test, y_pred):.4f}"
                ]
            }

            # Display as a static, clean table
            st.table(pd.DataFrame(summary_data))

            # Confusion Matrix (Visual)
            st.markdown("### Confusion Matrix")
            fig, ax = plt.subplots(figsize=(6, 4))
            cm = confusion_matrix(y_test, y_pred)
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
            plt.xlabel('Predicted Diagnosis')
            plt.ylabel('Actual Diagnosis')
            st.pyplot(fig)

            # Detailed Report
            st.subheader(" Classification Report")
            st.code(classification_report(y_test, y_pred))

        except Exception as e:
            st.error(f"Error during prediction: {e}")
            st.info("Ensure your uploaded CSV features match the training data format.")

elif uploaded_file is None:
    st.info("Please upload a CSV file to proceed. You can use 'test_breast_cancer.csv' generated by training script.")
